[package]
name = "vecstore"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = "0.9.1"
candle-nn = "0.9.1"
candle-transformers = "0.9.1"
anyhow = "1.0"
hf-hub = "0.3"
image = "0.25.6"
tokenizers = "0.15"
tokio = { version = "1", features = ["full", "rt-multi-thread"] }
serde_json = "1.0.140"
serde = { version = "1.0", features = ["derive"] }
tonic = "0.13.1"
axum = "0.8.4"
tower-http = { version = "0.5.0", features = ["cors"] }
http = "1.1.0"
