name: Vecstore Backend Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenSSL for cross-compilation
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config qemu-user-static libssl-dev gcc-aarch64-linux-gnu

      - name: Install cross
        run: cargo install cross

      - name: Build (aarch64-unknown-linux-gnu)
        run: cross build --target aarch64-unknown-linux-gnu --release

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "target/aarch64-unknown-linux-gnu/release/vecstore-back"
          target: "/home/ubuntu/vecstore-back"

      - name: SSH into VPS and Restart Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            chmod +x /home/ubuntu/vecstore-back
            sudo systemctl restart vecstore
